import { parseMarkdownTable } from "./test-output";

function cleanCode(text: string): string {
  return text.replace(/^```[a-z]*\n?/gm, "").replace(/^```$/gm, "").trim();
}

function slugify(s: string) {
  return s.slice(0, 40).replace(/\s+/g, "_").replace(/[^a-zA-Z0-9_-]/g, "").toLowerCase();
}

// ─── PDF ──────────────────────────────────────────────────────────────────────

export async function downloadPDF(type: string, text: string, title: string) {
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF({ orientation: type === "manual" ? "landscape" : "portrait", unit: "mm" });

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title.slice(0, 80), 14, 16);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text(`Type: ${type.toUpperCase()}  |  Generated by AITestCraft`, 14, 22);
  doc.setTextColor(0);

  if (type === "manual") {
    const parsed = parseMarkdownTable(text);
    if (parsed) {
      autoTable(doc, {
        startY: 28,
        head: [parsed.headers],
        body: parsed.rows,
        styles: { fontSize: 7, cellPadding: 2, overflow: "linebreak" },
        headStyles: { fillColor: [109, 40, 217], textColor: 255, fontStyle: "bold" },
        alternateRowStyles: { fillColor: [248, 245, 255] },
        columnStyles: { 0: { cellWidth: 18 } },
        margin: { left: 10, right: 10 },
      });
    } else {
      doc.setFont("courier", "normal");
      doc.setFontSize(8);
      doc.text(doc.splitTextToSize(text, 260), 14, 30);
    }
  } else {
    const code = cleanCode(text);
    doc.setFont("courier", "normal");
    doc.setFontSize(7.5);
    const lines = doc.splitTextToSize(code, 182);
    let y = 28;
    const pageH = doc.internal.pageSize.getHeight() - 15;
    for (const line of lines) {
      if (y > pageH) { doc.addPage(); y = 15; }
      doc.text(line, 14, y);
      y += 4;
    }
  }

  doc.save(`${slugify(title)}_${type}.pdf`);
}

// ─── Excel ────────────────────────────────────────────────────────────────────

export async function downloadExcel(type: string, text: string, title: string) {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();

  if (type === "manual") {
    const parsed = parseMarkdownTable(text);
    const data = parsed ? [parsed.headers, ...parsed.rows] : [[text]];
    const ws = XLSX.utils.aoa_to_sheet(data);
    if (parsed) {
      ws["!cols"] = parsed.headers.map((h) => ({ wch: Math.max(h.length + 2, 14) }));
    }
    XLSX.utils.book_append_sheet(wb, ws, "Test Cases");
  } else {
    const code = cleanCode(text);
    const ws = XLSX.utils.aoa_to_sheet(code.split("\n").map((l) => [l]));
    ws["!cols"] = [{ wch: 120 }];
    XLSX.utils.book_append_sheet(wb, ws, type === "bdd" ? "BDD Scenarios" : "Test Code");
  }

  XLSX.writeFile(wb, `${slugify(title)}_${type}.xlsx`);
}
